<?php exit();?>
{
    "base_resp": {
        "ret": 0,
        "err_msg": "ok",
        "cgi_name": ""
    },
    "debug_list": [{
        "title": "建立连接",
        "interfaces": [{
            "id": "1",
            "title": "获取AccessToken",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/gettoken",
            "method": "GET",
            "arguments": [{
                "name": "corpid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "公司的id"
            }, {
                "name": "corpsecret",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用sercret"
            }]
        }, {
            "id": "36",
            "title": "测试回调模式",
            "url": "",
            "method": "GET",
            "arguments": [{
                "name": "URL",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "开发者填写URL，调试时将把消息推送到该URL上"
            }, {
                "name": "Token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "Token"
            }, {
                "name": "EncodingAESKey",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "EncodingAESKey"
            }, {
                "name": "EchoStr",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "回文，只允许23个字节的数字"
            }, {
                "name": "ToUserName",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业CorpID"
            }]
        }]
    }, {
        "title": "管理通讯录",
        "interfaces": [{
            "id": "2",
            "title": "创建部门",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/department\/create",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "3",
            "title": "更新部门",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/department\/update",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "4",
            "title": "删除部门",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/department\/delete",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "id",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "部门id"
            }]
        }, {
            "id": "5",
            "title": "获取部门列表",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/department\/list",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            },{
                "name": "id",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "部门id"
            }]
        }, {
            "id": "6",
            "title": "创建成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/create",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "7",
            "title": "更新成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/update",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "8",
            "title": "删除成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/delete",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "userid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "员工UserID"
            }]
        }, {
            "id": "43",
            "title": "批量删除成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/batchdelete",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "9",
            "title": "获取成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/get",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "userid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "员工UserID"
            }]
        }, {
            "id": "10",
            "title": "获取部门成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/simplelist",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "department_id",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "部门id"
            }, {
                "name": "fetch_child",
                "must": false,
                "type": "text",
                "value": [""],
                "desc": "1\/0：是否递归获取子部门下面的成员"
            }, {
                "name": "status",
                "must": false,
                "type": "text",
                "value": [""],
                "desc": "0获取全部员工，1获取已关注成员列表，2获取禁用成员列表，4获取未关注成员列表。status可叠加"
            }]
        }, {
            "id": "59",
            "title": "获取部门成员(详情)",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/user\/list",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "department_id",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "获取的部门id"
            }, {
                "name": "fetch_child",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "1\/0：是否递归获取子部门下面的成员"
            }, {
                "name": "status",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "0获取全部成员，1获取已关注成员列表，2获取禁用成员列表，4获取未关注成员列表。status可叠加"
            }]
        },{
            "id": "45",
            "title": "异步邀请成员关注",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/batch\/inviteuser",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "46",
            "title": "异步增量更新成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/batch\/syncuser",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "47",
            "title": "异步全量覆盖成员",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/batch\/replaceuser",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "48",
            "title": "异步全量覆盖部门",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/batch\/replaceparty",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "49",
            "title": "获取异步任务结果",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/batch\/getresult",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "jobid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "异步任务id，最大长度为64字符"
            }]
        }]
    }, {
        "title": "管理素材文件",
        "interfaces": [{
            "id": "18",
            "title": "上传临时素材文件",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/media\/upload",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "type",
                "must": true,
                "type": "select",
                "value": ["image", "voice", "video", "file"],
                "desc": "媒体文件类型，分别有图片（image）、语音（voice）、视频（video），普通文件(file)"
            }, {
                "name": "media",
                "must": true,
                "type": "file",
                "value": [""],
                "desc": "form-data中媒体文件标识，有filename、filelength、content-type等信息"
            }]
        }, {
            "id": "19",
            "title": "获取临时素材文件",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/media\/get",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "media_id",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "媒体文件上传后获取的唯一标识"
            }]
        }]
    }, {
        "title": "管理企业应用",
        "interfaces": [{
            "id": "41",
            "title": "获取企业应用",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/agent\/get",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "agentid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "授权方应用id"
            }]
        }, {
            "id": "42",
            "title": "设置企业应用",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/agent\/set",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "67",
            "title": "获取应用概况列表",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/agent\/list",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }]
        }]
    }, {
        "title": "接收消息与事件",
        "interfaces": [{
            "id": "25",
            "title": "接收普通消息",
            "url": "",
            "method": "POST",
            "arguments": [{
                "name": "URL",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "开发者填写URL，调试时将把消息推送到该URL上"
            }, {
                "name": "Token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "Token"
            }, {
                "name": "EncodingAESKey",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "EncodingAESKey"
            }, {
                "name": "ToUserName",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业CorpID"
            }, {
                "name": "AgentID",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用的id，整型。可在应用的设置页面查看"
            }, {
                "name": "XML",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "回调数据XML"
            }]
        }, {
            "id": "30",
            "title": "接收事件",
            "url": "",
            "method": "POST",
            "arguments": [{
                "name": "URL",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "开发者填写URL，调试时将把消息推送到该URL上"
            }, {
                "name": "Token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "Token"
            }, {
                "name": "EncodingAESKey",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "EncodingAESKey"
            }, {
                "name": "ToUserName",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业CorpID"
            }, {
                "name": "AgentID",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用的id，整型。可在应用的设置页面查看"
            }, {
                "name": "XML",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "回调数据XML"
            }]
        }, {
            "id": "31",
            "title": "被动响应消息",
            "url": "",
            "method": "POST",
            "arguments": [{
                "name": "URL",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "开发者填写URL，调试时将把消息推送到该URL上"
            }, {
                "name": "Token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "Token"
            }, {
                "name": "EncodingAESKey",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "EncodingAESKey"
            }, {
                "name": "ToUserName",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业CorpID"
            }, {
                "name": "AgentID",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用的id，整型。可在应用的设置页面查看"
            }, {
                "name": "XML",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "回调数据XML"
            }]
        }]
    }, {
        "title": "发送消息",
        "interfaces": [{
            "id": "21",
            "title": "发送消息",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/message\/send",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }]
    }, {
        "title": "自定义菜单",
        "interfaces": [{
            "id": "22",
            "title": "创建应用菜单",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/menu\/create",
            "method": "POST",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "agentid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用的id，整型。可在应用的设置页面查看"
            }, {
                "name": "body",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口的数据json包"
            }]
        }, {
            "id": "23",
            "title": "删除菜单",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/menu\/delete",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "agentid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用的id，整型。可在应用的设置页面查看"
            }]
        }, {
            "id": "24",
            "title": "获取菜单列表",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/menu\/get",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }, {
                "name": "agentid",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "企业应用的id，整型。可在应用的设置页面查看"
            }]
        }]
    }, {
        "title": "企业微信JS-SDK接口",
        "interfaces": [{
            "id": "93",
            "title": "获取jsapi_ticket接口",
            "url": "https:\/\/qyapi.weixin.qq.com\/cgi-bin\/get_jsapi_ticket",
            "method": "GET",
            "arguments": [{
                "name": "access_token",
                "must": true,
                "type": "text",
                "value": [""],
                "desc": "调用接口凭证"
            }]
        }]
    }],
    "debug_count": 12,
    "debug_json": ""
}
